### PR TITLE
[IA-3975] Remove storage account from azure staging bucket name

### PR DESCRIPTION
**Pull request by LizBaldo**
@Qi77Qi noticed that the janitor cron job was down: https://ap-argocd.dsp-devops.broadinstitute.org/applications/leonardo-dev?resource=

The error can be tracked down to a change in how the Azure staging buckets are named:
`<storage account>/<storage container>` -> `<storage container>`

See more details in this slack thread: https://broadinstitute.slack.com/archives/GB1VAM14J/p1674163502629099

JIRA ticket https://broadworkbench.atlassian.net/browse/IA-3975

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
change lgtm....approving once assuming u've tested out the checker

**Comment by LizBaldo** [comment]
Yeah, sorry I forgot to mention but all tests touching leo DB are passing locally!

**Comment by Qi77Qi** [comment]
I meant testing by running the checker against dev DB...not unit tests

**Comment by LizBaldo** [comment]
I can confirm that running `checkStagingBucketsToRemove` against leo dev db does not throw any error :)

**Pull request merged**
