### PR TITLE
IA-2331 update deletedFrom

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-2331

### CODE REVIEW

**Review by kyuksel — APPROVED** [review]
LGTM 👍  My two cents would be to rename `deletedFrom` as `deletedBy` as the latter sounds more idiomatic to me.

**Comment by Qi77Qi** [comment]
@kyuksel yea..good idea....but it's probably more confusing if we call it `deletedBy` here but `deletedFrom` in actual database and in leonardo....

**Comment by kyuksel** [comment]
> it's probably more confusing if we call it deletedBy here but deletedFrom in actual database and in Leonardo....

For certain...I had meant we'd rename the column in Leo DB as well.

**Comment by Qi77Qi** [comment]
Sent a discussion in slack...doesn't seem like there's a strong preference. so going to merge the PR as is

**Pull request merged**
